/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DebugRealtimeRouteImport } from './routes/debug-realtime'
import { Route as TeamRouteRouteImport } from './routes/team/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as LoginTeamRouteImport } from './routes/login/team'
import { Route as JudgeEventSlugRouteImport } from './routes/judge/$eventSlug'
import { Route as DisplayEventSlugRouteImport } from './routes/display/$eventSlug'
import { Route as AdminTeamsRouteImport } from './routes/admin/teams'
import { Route as PublicEventSlugIndexRouteImport } from './routes/public/$eventSlug/index'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as PublicEventSlugTvRouteImport } from './routes/public/$eventSlug/tv'
import { Route as AdminEventsEventSlugRouteRouteImport } from './routes/admin/events/$eventSlug/route'
import { Route as AdminEventsEventSlugIndexRouteImport } from './routes/admin/events/$eventSlug/index'
import { Route as AdminEventsEventSlugRankingsRouteImport } from './routes/admin/events/$eventSlug/rankings'
import { Route as AdminEventsEventSlugMatchesRouteImport } from './routes/admin/events/$eventSlug/matches'
import { Route as AdminEventsEventSlugControlRouteImport } from './routes/admin/events/$eventSlug/control'

const DebugRealtimeRoute = DebugRealtimeRouteImport.update({
  id: '/debug-realtime',
  path: '/debug-realtime',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRouteRoute = TeamRouteRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRouteRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const LoginTeamRoute = LoginTeamRouteImport.update({
  id: '/login/team',
  path: '/login/team',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeEventSlugRoute = JudgeEventSlugRouteImport.update({
  id: '/judge/$eventSlug',
  path: '/judge/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayEventSlugRoute = DisplayEventSlugRouteImport.update({
  id: '/display/$eventSlug',
  path: '/display/$eventSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicEventSlugIndexRoute = PublicEventSlugIndexRouteImport.update({
  id: '/public/$eventSlug/',
  path: '/public/$eventSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PublicEventSlugTvRoute = PublicEventSlugTvRouteImport.update({
  id: '/public/$eventSlug/tv',
  path: '/public/$eventSlug/tv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsEventSlugRouteRoute =
  AdminEventsEventSlugRouteRouteImport.update({
    id: '/events/$eventSlug',
    path: '/events/$eventSlug',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminEventsEventSlugIndexRoute =
  AdminEventsEventSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminEventsEventSlugRouteRoute,
  } as any)
const AdminEventsEventSlugRankingsRoute =
  AdminEventsEventSlugRankingsRouteImport.update({
    id: '/rankings',
    path: '/rankings',
    getParentRoute: () => AdminEventsEventSlugRouteRoute,
  } as any)
const AdminEventsEventSlugMatchesRoute =
  AdminEventsEventSlugMatchesRouteImport.update({
    id: '/matches',
    path: '/matches',
    getParentRoute: () => AdminEventsEventSlugRouteRoute,
  } as any)
const AdminEventsEventSlugControlRoute =
  AdminEventsEventSlugControlRouteImport.update({
    id: '/control',
    path: '/control',
    getParentRoute: () => AdminEventsEventSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/debug-realtime': typeof DebugRealtimeRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/display/$eventSlug': typeof DisplayEventSlugRoute
  '/judge/$eventSlug': typeof JudgeEventSlugRoute
  '/login/team': typeof LoginTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/team/': typeof TeamIndexRoute
  '/admin/events/$eventSlug': typeof AdminEventsEventSlugRouteRouteWithChildren
  '/public/$eventSlug/tv': typeof PublicEventSlugTvRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/public/$eventSlug/': typeof PublicEventSlugIndexRoute
  '/admin/events/$eventSlug/control': typeof AdminEventsEventSlugControlRoute
  '/admin/events/$eventSlug/matches': typeof AdminEventsEventSlugMatchesRoute
  '/admin/events/$eventSlug/rankings': typeof AdminEventsEventSlugRankingsRoute
  '/admin/events/$eventSlug/': typeof AdminEventsEventSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/debug-realtime': typeof DebugRealtimeRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/display/$eventSlug': typeof DisplayEventSlugRoute
  '/judge/$eventSlug': typeof JudgeEventSlugRoute
  '/login/team': typeof LoginTeamRoute
  '/admin': typeof AdminIndexRoute
  '/login': typeof LoginIndexRoute
  '/team': typeof TeamIndexRoute
  '/public/$eventSlug/tv': typeof PublicEventSlugTvRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/public/$eventSlug': typeof PublicEventSlugIndexRoute
  '/admin/events/$eventSlug/control': typeof AdminEventsEventSlugControlRoute
  '/admin/events/$eventSlug/matches': typeof AdminEventsEventSlugMatchesRoute
  '/admin/events/$eventSlug/rankings': typeof AdminEventsEventSlugRankingsRoute
  '/admin/events/$eventSlug': typeof AdminEventsEventSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/team': typeof TeamRouteRouteWithChildren
  '/debug-realtime': typeof DebugRealtimeRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/display/$eventSlug': typeof DisplayEventSlugRoute
  '/judge/$eventSlug': typeof JudgeEventSlugRoute
  '/login/team': typeof LoginTeamRoute
  '/admin/': typeof AdminIndexRoute
  '/login/': typeof LoginIndexRoute
  '/team/': typeof TeamIndexRoute
  '/admin/events/$eventSlug': typeof AdminEventsEventSlugRouteRouteWithChildren
  '/public/$eventSlug/tv': typeof PublicEventSlugTvRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/public/$eventSlug/': typeof PublicEventSlugIndexRoute
  '/admin/events/$eventSlug/control': typeof AdminEventsEventSlugControlRoute
  '/admin/events/$eventSlug/matches': typeof AdminEventsEventSlugMatchesRoute
  '/admin/events/$eventSlug/rankings': typeof AdminEventsEventSlugRankingsRoute
  '/admin/events/$eventSlug/': typeof AdminEventsEventSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/team'
    | '/debug-realtime'
    | '/admin/teams'
    | '/display/$eventSlug'
    | '/judge/$eventSlug'
    | '/login/team'
    | '/admin/'
    | '/login/'
    | '/team/'
    | '/admin/events/$eventSlug'
    | '/public/$eventSlug/tv'
    | '/admin/events/'
    | '/public/$eventSlug/'
    | '/admin/events/$eventSlug/control'
    | '/admin/events/$eventSlug/matches'
    | '/admin/events/$eventSlug/rankings'
    | '/admin/events/$eventSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/debug-realtime'
    | '/admin/teams'
    | '/display/$eventSlug'
    | '/judge/$eventSlug'
    | '/login/team'
    | '/admin'
    | '/login'
    | '/team'
    | '/public/$eventSlug/tv'
    | '/admin/events'
    | '/public/$eventSlug'
    | '/admin/events/$eventSlug/control'
    | '/admin/events/$eventSlug/matches'
    | '/admin/events/$eventSlug/rankings'
    | '/admin/events/$eventSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/team'
    | '/debug-realtime'
    | '/admin/teams'
    | '/display/$eventSlug'
    | '/judge/$eventSlug'
    | '/login/team'
    | '/admin/'
    | '/login/'
    | '/team/'
    | '/admin/events/$eventSlug'
    | '/public/$eventSlug/tv'
    | '/admin/events/'
    | '/public/$eventSlug/'
    | '/admin/events/$eventSlug/control'
    | '/admin/events/$eventSlug/matches'
    | '/admin/events/$eventSlug/rankings'
    | '/admin/events/$eventSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  TeamRouteRoute: typeof TeamRouteRouteWithChildren
  DebugRealtimeRoute: typeof DebugRealtimeRoute
  DisplayEventSlugRoute: typeof DisplayEventSlugRoute
  JudgeEventSlugRoute: typeof JudgeEventSlugRoute
  LoginTeamRoute: typeof LoginTeamRoute
  LoginIndexRoute: typeof LoginIndexRoute
  PublicEventSlugTvRoute: typeof PublicEventSlugTvRoute
  PublicEventSlugIndexRoute: typeof PublicEventSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/debug-realtime': {
      id: '/debug-realtime'
      path: '/debug-realtime'
      fullPath: '/debug-realtime'
      preLoaderRoute: typeof DebugRealtimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRouteRoute
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/login/team': {
      id: '/login/team'
      path: '/login/team'
      fullPath: '/login/team'
      preLoaderRoute: typeof LoginTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/$eventSlug': {
      id: '/judge/$eventSlug'
      path: '/judge/$eventSlug'
      fullPath: '/judge/$eventSlug'
      preLoaderRoute: typeof JudgeEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$eventSlug': {
      id: '/display/$eventSlug'
      path: '/display/$eventSlug'
      fullPath: '/display/$eventSlug'
      preLoaderRoute: typeof DisplayEventSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/public/$eventSlug/': {
      id: '/public/$eventSlug/'
      path: '/public/$eventSlug'
      fullPath: '/public/$eventSlug/'
      preLoaderRoute: typeof PublicEventSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/events'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/public/$eventSlug/tv': {
      id: '/public/$eventSlug/tv'
      path: '/public/$eventSlug/tv'
      fullPath: '/public/$eventSlug/tv'
      preLoaderRoute: typeof PublicEventSlugTvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events/$eventSlug': {
      id: '/admin/events/$eventSlug'
      path: '/events/$eventSlug'
      fullPath: '/admin/events/$eventSlug'
      preLoaderRoute: typeof AdminEventsEventSlugRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/events/$eventSlug/': {
      id: '/admin/events/$eventSlug/'
      path: '/'
      fullPath: '/admin/events/$eventSlug/'
      preLoaderRoute: typeof AdminEventsEventSlugIndexRouteImport
      parentRoute: typeof AdminEventsEventSlugRouteRoute
    }
    '/admin/events/$eventSlug/rankings': {
      id: '/admin/events/$eventSlug/rankings'
      path: '/rankings'
      fullPath: '/admin/events/$eventSlug/rankings'
      preLoaderRoute: typeof AdminEventsEventSlugRankingsRouteImport
      parentRoute: typeof AdminEventsEventSlugRouteRoute
    }
    '/admin/events/$eventSlug/matches': {
      id: '/admin/events/$eventSlug/matches'
      path: '/matches'
      fullPath: '/admin/events/$eventSlug/matches'
      preLoaderRoute: typeof AdminEventsEventSlugMatchesRouteImport
      parentRoute: typeof AdminEventsEventSlugRouteRoute
    }
    '/admin/events/$eventSlug/control': {
      id: '/admin/events/$eventSlug/control'
      path: '/control'
      fullPath: '/admin/events/$eventSlug/control'
      preLoaderRoute: typeof AdminEventsEventSlugControlRouteImport
      parentRoute: typeof AdminEventsEventSlugRouteRoute
    }
  }
}

interface AdminEventsEventSlugRouteRouteChildren {
  AdminEventsEventSlugControlRoute: typeof AdminEventsEventSlugControlRoute
  AdminEventsEventSlugMatchesRoute: typeof AdminEventsEventSlugMatchesRoute
  AdminEventsEventSlugRankingsRoute: typeof AdminEventsEventSlugRankingsRoute
  AdminEventsEventSlugIndexRoute: typeof AdminEventsEventSlugIndexRoute
}

const AdminEventsEventSlugRouteRouteChildren: AdminEventsEventSlugRouteRouteChildren =
  {
    AdminEventsEventSlugControlRoute: AdminEventsEventSlugControlRoute,
    AdminEventsEventSlugMatchesRoute: AdminEventsEventSlugMatchesRoute,
    AdminEventsEventSlugRankingsRoute: AdminEventsEventSlugRankingsRoute,
    AdminEventsEventSlugIndexRoute: AdminEventsEventSlugIndexRoute,
  }

const AdminEventsEventSlugRouteRouteWithChildren =
  AdminEventsEventSlugRouteRoute._addFileChildren(
    AdminEventsEventSlugRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEventsEventSlugRouteRoute: typeof AdminEventsEventSlugRouteRouteWithChildren
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminTeamsRoute: AdminTeamsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEventsEventSlugRouteRoute: AdminEventsEventSlugRouteRouteWithChildren,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface TeamRouteRouteChildren {
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteRouteChildren: TeamRouteRouteChildren = {
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteRouteWithChildren = TeamRouteRoute._addFileChildren(
  TeamRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  TeamRouteRoute: TeamRouteRouteWithChildren,
  DebugRealtimeRoute: DebugRealtimeRoute,
  DisplayEventSlugRoute: DisplayEventSlugRoute,
  JudgeEventSlugRoute: JudgeEventSlugRoute,
  LoginTeamRoute: LoginTeamRoute,
  LoginIndexRoute: LoginIndexRoute,
  PublicEventSlugTvRoute: PublicEventSlugTvRoute,
  PublicEventSlugIndexRoute: PublicEventSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
